### ISSUE TITLE
Facts and events of inverse associates: Text and position of icons

### ISSUE THREAD

**Issue by Gunnar-GO** [vesta-webtrees-2-custom-modules/vesta_personal_facts#2]
The basic Facts and events set Name and below the icons.

the extented facts switch this behavior: icons on top, names below. least by residence information, birth and death is correct.
So it is mixed (webtrees 2.0.1 , FAB + Compact Themes Adjuster).

// it applies to residence connected with family of the person.

**Comment by ric2016** [comment]
I don't understand - Do you mean the name of the fact/event sometimes appears below the icons for editing etc.? Do you have a screenshot?

**Comment by Gunnar-GO** [comment]
![screenshot](https://user-images.githubusercontent.com/24938625/72108456-f382b680-3333-11ea-8967-85c8592214da.jpg)

**Comment by ric2016** [comment]
Thanks - So this occurs for "Facts and events of inverse associates" (but apparently not for family facts and events). 

Two things:
I have intentionally disabled the regular edit buttons (as they are in fact broken in the original tab for these kinds of facts and events, and anyway just seem confusing in this context).

I have also adjusted the text in specific cases. The original tab has "Christening" etc., which is confusing: It's actually something like "Godfather at a christening" (similar to "Death of a father" rather than "Death" etc). "Residence" and all other facts and events should be adjusted similarly ("Associate with regard to a residence" or something like that), I'll fix that.

I agree that the (remaining) icons should be positioned consistently, I'll adjust that as well.

**Comment by Gunnar-GO** [comment]
thx :)
