### ISSUE TITLE
First show text, then show pictures

### ISSUE THREAD

**Issue by SnarfW** [vesta-webtrees-2-custom-modules/vesta_personal_facts#99]
I have quite a number of media objects in my tree. Because of these images (in combination with maybe not the fastest server) I do see a difference between your module and the 'standard' personal facts and events module: 
In the 'webtrees original' personal facts and events module, first the text is loaded and then the images. (So the page is slowly build up when a lot of images are attached to the person).
In your custom module both are shown at the same time, and only after the thumbnails of the images have been generated. Therefor for a page with several images it can take quite a while before any information is shown.

Would it be possible to implement the same behaviour as in the original/standard module: immediately show the text and then slowly show the images?

**Comment by ric2016** [comment]
I can reproduce this by adding a delay in MediaFileThumbnail.php.

It is caused by the flag "canLoadAjax", which is set to true to the Vesta tab (in order to avoid unnecessary requests when the tab isn't actually displayed), but not for the original tab. I'm not sure about the best way to fix this.

Tabs loaded via ajax are apparently only displayed once they are fully ready ([see comment here](https://github.com/fisharebest/webtrees/blob/a9d9efe552b5c781d5c218145bc37c92abc1a95d/resources/views/individual-page-tabs.phtml#L45)).

Does it help if you remove (or comment out) lines 46 and 50 in this file (keeping the lines in between)?

Alternatively, setting "canLoadAjax" to true [here](https://github.com/vesta-webtrees-2-custom-modules/vesta_personal_facts/blob/fbfe46421374c7d4459a21074a325ff89192f5a2/IndividualFactsTabModuleExtended.php#L135) should also help (but break other things according to the comment there), but I'd prefer to offer the first workaround as an option (or change to that in general).

**Comment by ric2016** [comment]
Option to disable the ajax loading added in Release 2.1.20.2.0.
